=== IBM/waiops-tech-jam/labs/cloud-pak-aiops/alert-lab-1/3-alert-concepts/images/normalizedEventSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Normalized Event schema",
    "description": "Normalized Event for None mapping use case",
    "type": "object",
    "properties": {
        "sender": {
            "description": "Identifies the resource which sent this event. This may be the resource that is the subject of the event, or it may be some external system which is monitoring the subject.",
            "type": "object",
            "properties": {
                "service": {
                    "description": "The identifier of the service",
                    "type": "string"
                },
                "name": {
                    "description": "The descriptive name of the service",
                    "type": "string"
                },
                "type": {
                    "description": "Data source name. For examples, PagerDuty, Netcool/OMNIbus",
                    "type": "string"
                }
            },
            "required": [
                "service",
                "name",
                "type"
            ]
        },
        "resource": {
            "description": "Identifies the resource that is the subject of this event. This is made up of multiple fields that describe the resource. There are a set of standard fields which should be used where applicable, but additional fields may be set.",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the resource. For example, myhost.example.com",
                    "type": "string"
                },
                "hostname": {
                    "description": "The hostname of the resource.",
                    "type": "string"
                },
                "type": {
                    "description": "The type of resource. For example, host",
                    "type": "string"
                },
                "ipaddress": {
                    "description": "The IP address of the resource.",
                    "type": "string"
                },
                "location": {
                    "description": "The location of the resource. For example, Dallas 10",
                    "type": "string"
                }
            },
            "required": [
                "name",
                "hostname",
                "type",
                "ipaddress",
                "location"
            ]
        },
        "type": {
            "description": "Indicates whether the source alert is a problem or a resolution along with its classification.",
            "type": "object",
            "properties": {
                "classification": {
                    "description": "Description of the type of the event. E.g. Utilization, System status, Threshold breach",
                    "type": "string"
                },
                "eventType": {
                    "description": "String description of whether the event is 'problem' or 'resolution'. Note: Only these two values are permitted.",
                    "type": "string"
                }
            },
            "required": [
                "classification",
                "eventType"
            ]
        },
        "severity": {
            "description": "Indicates the event severity level, which indicates how the perceived capability of the managed object has been affected.",
            "type": "integer",
            "minimum": 0,
            "maximum": 6
        },
        "summary": {
            "description": "A human-readable description of the event.",
            "type": "string"
        },
        "occurrenceTime": {
            "description": "The time at which this event occurred. (ISO format: yyyy-mm-ddThh:mm:ss.SSSZ)",
            "type": "string",
            "pattern": "\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)Z"
        },
        "expirySeconds": {
            "description": "The number of seconds before the event should automatically expire. A value of zero indicates that there is no expiration.",
            "type": "integer",
            "minimum": 0
        }
    },
    "required": [
        "sender",
        "resource",
        "type",
        "severity",
        "summary",
        "occurrenceTime",
        "expirySeconds"
    ]
}

=== IBM/waiops-tech-jam/labs/cloud-pak-aiops/alert-correlation/1-introduction/images/sampleEvent.json
{
    "sender": {
        "service": "Mun SelfMonitoring",
        "name": "Mun SelfMonitoring",
        "type": "Datadog Observability"
    },
    "resource": {
        "name": "AGG_P",
        "hostname": "samplehost.ibm.com",
        "type": "host",
        "ipaddress": "10.1.96.24",
        "location": "Dal10"
    },
    "type": {
        "classification": "CEASelfMonitoring",
        "eventType": "problem"
    },
    "severity": 6,
    "summary": "Web Service - getTransferAmount() timeout",
    "occurrenceTime": "2023-05-05T14:50:38.000Z",
    "expirySeconds": 0
}
